from __future__ import annotations
# -*- coding: utf-8 -*-
# code generated by Prisma. DO NOT EDIT.
# fmt: off
# -- template metadata.py.jinja --


PRISMA_MODELS: set[str] = {
    'Project',
    'Task',
    'Worker',
    'Assignment',
    'Log',
}

RELATIONAL_FIELD_MAPPINGS: dict[str, dict[str, str]] = {
    'Project': {
        'tasks': 'Task',
    },
    'Task': {
        'project': 'Project',
        'assignedWorker': 'Worker',
        'assignments': 'Assignment',
    },
    'Worker': {
        'tasks': 'Task',
        'assignments': 'Assignment',
    },
    'Assignment': {
        'task': 'Task',
        'worker': 'Worker',
    },
    'Log': {
    },
}

# fmt: on